version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: dubbingai-postgres
    restart: always
    environment:
      POSTGRES_USER: dubbingai
      POSTGRES_PASSWORD: dubbingai123
      POSTGRES_DB: dubbingai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: dubbingai-redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: dubbingai-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  pgdata: